--- 
- hosts: all
  gather_facts: true
  become: true
  become_user: centos
  tasks:
  - name: Deploy War File
    maven_artifact: group_id=org.bharath artifact_id=application extension=war repository_url=http://54.153.77.32:8080/nexus/content/repositories/snapshots/bharath/org/application/1.0-SNAPSHOT/ username=admin password=admin123  dest=~/usr/hold/
    
  - name: c
    command: scp -r -i /var/lib/jenkins/workspace/CD/Task.pem /usr/hold centos@52.53.243.43:/usr/share/tomcat/webapps/
      
  - name: restart tomcat
    command: service tomcat restart 
 
    
    

